version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
